# Generated by Django 4.2.4 on 2023-08-26 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "generate_logo",
                    models.BooleanField(default=False, verbose_name="Сгенерировать логотип"),
                ),
                (
                    "generate_name",
                    models.BooleanField(default=False, verbose_name="Сгенерировать название"),
                ),
                (
                    "checko_url",
                    models.URLField(default=None, null=True, verbose_name="Ссылка на Checko"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Презентация",
                "verbose_name_plural": "Презентации",
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        default=None, null=True, upload_to="logos", verbose_name="Логотип"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=None, max_length=100, null=True, verbose_name="Название"
                    ),
                ),
                ("pptx_data", models.JSONField(default=None, null=True, verbose_name="JSON")),
                (
                    "pptx",
                    models.FileField(default=None, null=True, upload_to="", verbose_name="PPTX"),
                ),
                (
                    "name_status",
                    models.CharField(
                        default="Starting", max_length=100, verbose_name="Статус названия"
                    ),
                ),
                (
                    "logo_status",
                    models.CharField(
                        default="Starting", max_length=100, verbose_name="Статус логотипа"
                    ),
                ),
                (
                    "pptx_status",
                    models.CharField(
                        default="Starting", max_length=100, verbose_name="Статус PPTX"
                    ),
                ),
                (
                    "presentation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.presentation",
                        verbose_name="Презентация",
                    ),
                ),
            ],
        ),
    ]
