# Generated by Django 4.2.4 on 2023-08-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_result_logo_status_alter_result_name_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="checko_url",
            field=models.CharField(default=None, max_length=20, null=True, verbose_name="ИНН"),
        ),
    ]
