# Generated by Django 4.2.4 on 2023-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Администратор"),
        ),
    ]
